### This notebook loads in the model that was trained in my 'DL_categorical-fastai' notebook. I have created a 'predictor' function which will make predictions of the number of likes that your comment will receive based on the text provided, and show examples of calling this function below.

In [19]:
# Import libraries and then load my model. 
#Because the cuDNN libraries tend to fail to load the first time, I have the code try again on an exception error to make it work the second time.

from fastai.text import *
from fastai.basics import *
try:    
    from keras.backend.tensorflow_backend import set_session
    import tensorflow as tf
    
    config = tf.ConfigProto()
    config.gpu_options.allow_growth = True  # dynamically grow the memory used on the GPU
    config.log_device_placement = True  # to log device placement (on which device the operation ran)
    sess = tf.Session(config=config)
    set_session(sess)  # set thi

    path = r'C:\Users\msteele9\Documents\Springboard\Springboard\Notebooks'
    learn = load_learner(path, 'trained_model.pkl')
except:
    from keras.backend.tensorflow_backend import set_session
    import tensorflow as tf
    
    config = tf.ConfigProto()
    config.gpu_options.allow_growth = True  # dynamically grow the memory used on the GPU
    config.log_device_placement = True  # to log device placement (on which device the operation ran)
    sess = tf.Session(config=config)
    set_session(sess)  # set thi

    path = "models/"
    learn = load_learner(path, 'fit_lstm_binary_5k.pth')

In [30]:
# This function will take a comment and make a prediction based on the content.

def predictor(test_comment):
 
    cat, tensor, probs = learn.predict(test_comment)
    print(probs)
    
    category = str(cat)
    
    if category == 0: print('This comment is predicted to be unpopular and receive no likes.') 
    else: print('This comment is predicted to be popular and receive some likes.')
        
    
    
    

In [31]:
try:
    predictor("This is a test of the emergency comment system that was placed in category 2 ")
except:
    predictor("This is a test of the emergency comment system that was placed in category 2 ")

C:\Users\msteele9\AppData\Local\Continuum\anaconda3_reinstall\envs\fastai_v1\lib\site-packages\fastai\torch_core.py:83: UserWarning: Tensor is int32: upgrading to int64; for better performance use int64 input
  warn('Tensor is int32: upgrading to int64; for better performance use int64 input')


tensor([0.3078, 0.2850, 0.4072])
This comment is predicted to be popular and receive some likes.


In [32]:
string = "Category 0"
predictor(string)

C:\Users\msteele9\AppData\Local\Continuum\anaconda3_reinstall\envs\fastai_v1\lib\site-packages\fastai\torch_core.py:83: UserWarning: Tensor is int32: upgrading to int64; for better performance use int64 input
  warn('Tensor is int32: upgrading to int64; for better performance use int64 input')


tensor([0.5353, 0.2976, 0.1672])
This comment is predicted to be popular and receive some likes.


In [33]:
if len(sys.argv) > 0:
    for arg in sys.argv:
        string = arg
        rec = predictor(string)
        print("\n")
        print(string)
        print(rec)
        print("\n")

C:\Users\msteele9\AppData\Local\Continuum\anaconda3_reinstall\envs\fastai_v1\lib\site-packages\fastai\torch_core.py:83: UserWarning: Tensor is int32: upgrading to int64; for better performance use int64 input
  warn('Tensor is int32: upgrading to int64; for better performance use int64 input')


tensor([0.9267, 0.0617, 0.0116])
This comment is predicted to be popular and receive some likes.


C:\Users\msteele9\AppData\Local\Continuum\anaconda3_reinstall\envs\fastai_v1\lib\site-packages\ipykernel_launcher.py
None




C:\Users\msteele9\AppData\Local\Continuum\anaconda3_reinstall\envs\fastai_v1\lib\site-packages\fastai\torch_core.py:83: UserWarning: Tensor is int32: upgrading to int64; for better performance use int64 input
  warn('Tensor is int32: upgrading to int64; for better performance use int64 input')


tensor([0.5935, 0.2734, 0.1331])
This comment is predicted to be popular and receive some likes.


-f
None




C:\Users\msteele9\AppData\Local\Continuum\anaconda3_reinstall\envs\fastai_v1\lib\site-packages\fastai\torch_core.py:83: UserWarning: Tensor is int32: upgrading to int64; for better performance use int64 input
  warn('Tensor is int32: upgrading to int64; for better performance use int64 input')


tensor([0.8604, 0.1135, 0.0261])
This comment is predicted to be popular and receive some likes.


C:\Users\msteele9\AppData\Roaming\jupyter\runtime\kernel-56b35603-13ed-44e6-9a34-5c0698195c27.json
None


